# Set the text alignment in posts / pages.
text_align:
  # Available values: start | end | left | right | center | justify | justify-all | match-parent
  desktop: justify-all
  mobile: justify-all
title: Kun Qian (钱坤)
logo: /assets/img/photo.jpg
description: Research Scientist <br> Network Research at Alibaba Cloud <br> Email: kunqian.qk@alibaba-inc.com
#show_downloads: true
#google_analytics:
#theme: jekyll-theme-minimal
